export default {
    FETCH_EVENTS: 'FETCH_EVENTS',
    FETCH_EVENTS_SUCCESS: 'FETCH_EVENTS_SUCCESS',
    FETCH_FAILED: 'FETCH_FAILED',
    PREVIOUS_PAGE: 'PREVIOUS_PAGE',
    NEXT_PAGE: 'NEXT_PAGE',
}